# Generated by Django 5.1.7 on 2025-03-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=250)),
                ('event_discription', models.CharField(max_length=300)),
                ('event_chategory', models.CharField(max_length=250)),
                ('event_date', models.DateField(verbose_name='')),
                ('event_time', models.IntegerField(verbose_name='')),
                ('event_status', models.CharField(max_length=200)),
                ('event_capacity', models.IntegerField(verbose_name='')),
                ('event_seatManagement', models.BooleanField(default=False)),
                ('event_age_limit', models.IntegerField(verbose_name='')),
                ('event_duration', models.IntegerField(verbose_name='')),
                ('event_price', models.FloatField(verbose_name='')),
                ('event_location', models.CharField(max_length=250)),
            ],
        ),
    ]
