# Generated by Django 5.1.7 on 2025-03-31 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_age_limit',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_duration',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_seatManagement',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_status',
        ),
    ]
