# Generated by Django 5.1.7 on 2025-03-31 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_booking_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='event_chategory',
            new_name='event_category',
        ),
    ]
