# Generated by Django 5.1.7 on 2025-04-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_event_chategory_events_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='booking',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
