# Generated by Django 5.1.7 on 2025-04-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_ticket_booking_delete_booking_delete_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_capacity',
            field=models.TimeField(verbose_name=''),
        ),
    ]
