# Generated by Django 5.1.7 on 2025-04-03 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
    ]
