# Generated by Django 5.1.7 on 2025-04-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(verbose_name=''),
        ),
    ]
