# Generated by Django 5.1.7 on 2025-04-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_rename_events_booking_event_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user_name',
            new_name='user',
        ),
    ]
