# Generated by Django 5.1.7 on 2025-04-06 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
    ]
